(신수녕) 메인페이지, 엔트리 페이지 레이아웃 완성
cozynye/WebRTC-APPLICATION-frontend pull request #1
Opened 2022-02-28 06:49 UTC by cozynye

## :: 구현 목표
- 메인페이지, 엔트리 페이지 레이아웃

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 엔트리 페이지
- 회사 로고 이미지 파일과 회원가입, 로그인 버튼 배치
- 앱 실행 시 상단에 Entry라 적혀 있는데 그 부분 사라지는 방법 찾아야 합니다

2. 로그인 페이지
- 회사 로고 이미지, 이메일과 비밀번호 textinput 박스, 로그인 버튼 배치
- 엔트리와 마찬가지로 상단에 SignIn 글자가 있는데 사라지게 하고 레이아웃 조정이 필요합니다.
- 현재 로그인 버튼에 이벤트는 걸어놓지 않았습니다.

<br />

## :: 기타 질문 및 특이 사항
- 리액트 네이티브에서 styled-components 쓸 때 nth:child를 쓰고 싶은데 적용이 안되는 것 같습니다. 네이티브에서는 아직 활용을 못하는 것인가요?
-타입스크립트를 좀더 공부하고 고쳐야할 소스가 많은 것 같습니다.

2022-02-28 07:11 UTC, LEEYEONSEONG commented on src/screens/SignIn.tsx
> +  console.log(inputState);
console.log()는 삭제해주세요.!!

2022-02-28 07:11 UTC, LEEYEONSEONG commented on src/screens/SignIn.tsx
> +            value={inputState.email}
destructuring을 습관화 해주시면 좋습니다.!!

2022-02-28 07:11 UTC, Enjoywater commented on src/screens/Entry.tsx
> +  background-color: ${props => props.theme.color.white};
매번 `props.theme.--` 로 불러오는 것 보다,
구조분해를 하시거나, `ThemeProvider`를 사용하시지 않는것도 좋은 방법이 될 수 있습니다.

2022-02-28 07:20 UTC, cozynye commented on src/screens/SignIn.tsx
> +  console.log(inputState);
네 알겠습니다!

2022-02-28 07:27 UTC, cozynye commented on src/screens/Entry.tsx
> +  background-color: ${props => props.theme.color.white};
구조분해는 어떻게 하는지 알겠는데 ThemeProvider을 사용하지 않고 쓰려면 임포트 해서 쓰는 방법을 말씀하시는 게 맞을까요? 🤔

2022-02-28 07:27 UTC, cozynye commented on src/screens/SignIn.tsx
> +            value={inputState.email}
수정하겠습니다!

2022-02-28 07:32 UTC, Enjoywater commented on src/screens/Entry.tsx
> +  background-color: ${props => props.theme.color.white};
color를 import해서 사용하거나,
:root와 var() 를 이용할 수 있습니다~!

2022-02-28 07:40 UTC, jasonkang14 requested changes

2022-02-28 07:40 UTC, jasonkang14 commented on src/styles/theme.tsx
> +import {DefaultTheme} from 'styled-components/native';
React Component를 리턴하지 않는 경우 파일 확장자를 `.ts`로 변경해주세요

2022-02-28 08:04 UTC, cozynye commented on src/styles/theme.tsx
> +import {DefaultTheme} from 'styled-components/native';
수정했습니다!

2022-02-28 09:01 UTC, jasonkang14 requested changes
수녕님과 승현님이 상의하셔서 styled-components를 사용할 때 파일명에 컨벤션이 있으면 좋을 것 같습니다. comment확인해주세요!

2022-02-28 09:01 UTC, jasonkang14 commented on babel.config.js
> +          '@images': './assets/images',
`assets` 디렉토리는 `src` 디렉토리 밖에 위치하는 이유가 있나요?

2022-02-28 09:01 UTC, jasonkang14 commented on package.json
> +    "node-sass": "^7.0.1",
style관련 패키지는 하나만 사용해주세요.

2022-02-28 09:01 UTC, jasonkang14 commented on package.json
> +    "node-sass": "^7.0.1",
react native에서 sass를 사용하려면 추가로 패키지를 설치해야해서 styled-components를 사용하는 편이 좋아보입니다

2022-02-28 09:01 UTC, jasonkang14 commented on src/screens/Entry.tsx
> +  navigation: StackNavigationProp<any>;
`any`의 사용은 지양해주세요

2022-02-28 09:01 UTC, jasonkang14 commented on src/screens/Entry.tsx
> +        <Image source={require('@images/logo.png')} />
import를 사용하는 방식으로 수정해주세요

2022-02-28 09:01 UTC, jasonkang14 commented on src/screens/Entry.tsx
> +const Image = styled.Image``;
이런 경우에는 따로 선언하는 것이 불필요해보이네요

2022-02-28 09:01 UTC, jasonkang14 commented on src/screens/Entry.tsx
> +  margin-top: 272px;
리액트 네이티브에서 스타일은 [flexbox](https://reactnative.dev/docs/flexbox)를 사용합니다. 
`margin-top: 272px` 보다는 [flexbox속성들](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)을 사용해서 잔여 영역의 가운데에 위치하도록 수정해주세요

2022-02-28 09:01 UTC, jasonkang14 commented on src/screens/SignIn.tsx
> +        <Image source={require('@images/logo.png')} />
여기도 import 하는 방식으로 수정해주세요

2022-02-28 09:01 UTC, jasonkang14 commented on src/screens/SignIn.tsx
> +  flex: 2;
좋습니다 👍

2022-02-28 09:26 UTC, cozynye commented on babel.config.js
> +          '@images': './assets/images',
리액트에서는 public 디렉토리 안에 넣어 관리 했는데 여기는 없어서 최상단에 뒀는데 src 디렉토리안에 넣는 것이 좋을까요?

2022-02-28 09:26 UTC, cozynye commented on package.json
> +    "node-sass": "^7.0.1",
패키지 삭제했습니다!

2022-03-01 13:22 UTC, jasonkang14 reviewed
폰트 추가와 react-native-vector-icons라는 패키지를 설치한 목적이 무엇인가요?

제플린에 보시면, 사용된 폰트는 NotoSans가 유일하고, 

제가 이해하기로는 react-native-vector-icons는 [Icon Explorer](https://oblador.github.io/react-native-vector-icons/)에서 아이콘을 사용할 수 있게 도와주는데, 디자이너분이 제공한 디자인이 있는데 무료 아이콘을 사용하는 이유가 있을까요?

2022-03-01 13:22 UTC, jasonkang14 commented on android/app/src/main/java/com/webrtc/MainApplication.java
> +import com.oblador.vectoricons.VectorIconsPackage;
이 패키지는 왜 필요한가요?

2022-03-01 13:22 UTC, jasonkang14 commented on ios/WebRTC/Info.plist
> +	<key>UIAppFonts</key>
제플린에 보시면 사용되는 폰트는 NotoSans하나인데, 다른 폰트를 추가하신 이유가 있나요?

2022-03-01 13:22 UTC, jasonkang14 commented on package.json
> +    "react-native-vector-icons": "^9.1.0",
이 패키지의 목적이 뭔가요?

2022-03-02 01:56 UTC, cozynye commented on android/app/src/main/java/com/webrtc/MainApplication.java
> +import com.oblador.vectoricons.VectorIconsPackage;
디자인을 사용하고 패키지 삭제했습니다!

2022-03-02 01:56 UTC, cozynye commented on ios/WebRTC/Info.plist
> +	<key>UIAppFonts</key>
벡터 아이콘을 쓰려면 추가했어야 했는데 패키지 삭제로 인해 추가한 부분 삭제했습니다!

2022-03-02 01:57 UTC, cozynye commented on package.json
> +    "react-native-vector-icons": "^9.1.0",
splash 사용법 찾아보다가 패키지 설치 관련건 있었는데 다시 한번 확인해보고 불필요할 시 삭제하도록 하겠습니다

2022-03-03 09:51 UTC, Enjoywater commented on src/screens/Main.tsx
> +    if (auth.token === undefined || auth.token === null) {
조건이 `falsy`값을 나타내기 때문에 `NOT`연산자로 한번에 표현이 가능합니다.

2022-03-03 09:51 UTC, Enjoywater commented on src/screens/SignIn.tsx
> +              secureTextEntry={isPasswordType ? true : false}
위 useState에 사용된 `isPasswordType` 값 자체가 `boolean`값이기 때문에 삼항연산자는 불필요해보입니다.

2022-03-03 11:12 UTC, cozynye commented on src/screens/Main.tsx
> +    if (auth.token === undefined || auth.token === null) {
수정했습니다!

2022-03-03 11:12 UTC, cozynye commented on src/screens/SignIn.tsx
> +              secureTextEntry={isPasswordType ? true : false}
수정했습니다!!!😀

2022-03-03 12:53 UTC, jasonkang14 requested changes
`icon_feather_eye_on.png`, `icon_feather_eye_off.png`는 이미지가 잘못된 것 같고, 
`--background`라는 파일은 용도가 무엇인가요?

2022-03-03 12:53 UTC, jasonkang14 commented on android/app/src/main/java/com/webrtc/MainApplication.java
> +import com.oblador.vectoricons.VectorIconsPackage;
사용하지 않는다면 vector icon package를 제거해주세요.

2022-03-03 12:53 UTC, jasonkang14 commented on android/settings.gradle
> +include ':react-native-vector-icons'
사용하지 않는 package설정을 제거해주세요

2022-03-03 12:53 UTC, jasonkang14 commented on ios/WebRTC/Info.plist
> +	<array>
여기 폰트들도 사용하지 않는다면 제거해주세요. 모든 프로그래밍이 마찬가지겠지만 모바일 앱은 불필요한 파일 및 설정으로 용량이 커지면 performance에 큰 영향을 미칩니다

2022-03-03 12:53 UTC, jasonkang14 commented on package.json
> +    "@bam.tech/react-native-make": "^3.0.3",
이 패키지의 목적은 뭔가요?

2022-03-03 12:53 UTC, jasonkang14 commented on src/screens/Main.tsx
> +  }, [auth.token, navigation]);
navigation이 변할 때 마다 effect hook을 확인해야 하는건가요?

2022-03-03 12:53 UTC, jasonkang14 commented on src/screens/Main.tsx
> +        <Image source={MainImage} resizeMode="contain" style={{height: 337}} />
image src는 camelCase를 사용해주세요

2022-03-03 12:53 UTC, jasonkang14 commented on src/screens/Main.tsx
> +  right: -30px;
-30px의 목적은 무엇인가요?

2022-03-03 12:53 UTC, jasonkang14 commented on src/module/auth.ts
> +  action: {type: string; payload: string},
payload는 항상 string인가요?

2022-03-03 12:53 UTC, jasonkang14 commented on src/module/auth.ts
> +    case SET_TOEKN:
오타가있네요. `SET_TOKEN`

2022-03-03 12:53 UTC, jasonkang14 commented on src/screens/SignIn.tsx
> +      await fetch('http://44.203.41.15:8000/users/signin', {
API주소는 환경변수 또는 별도로 선언한 상수를 사용해주세요.

2022-03-03 12:53 UTC, jasonkang14 commented on src/screens/SignIn.tsx
> +          if (data.result === 'True') {
True가 boolean이 아니라 string으로 넘어오나요?

2022-03-03 12:55 UTC, jasonkang14 commented
이 PR은 규모가 너무 큽니다. 

`feature/signup`이라고 브랜치를 생성했다면, 
`signup`과 관련된 기능만 있어야하는데, 
여기에는 `signup`, `signin`, `signin` 후에 보여지는 화면까지 포함되어 있습니다. 

처음에 PR올리실 때 내용을 읽어보고 comment를 했어야했는데 놓쳤네요. 
내일 자세히 말씀 드리겠습니다!

2022-03-03 13:09 UTC, cozynye commented on package.json
> +    "@bam.tech/react-native-make": "^3.0.3",
스플래쉬 이미지 만드는 용도였는데 삭제하겠습니다!

2022-03-03 13:22 UTC, cozynye commented on src/screens/Main.tsx
> +  }, [auth.token, navigation]);
React Hook useEffect has a missing dependency: 'navigation'. Either include it or remove the dependency array
이렇게 있어서 추가했는데 지우는게 더 좋을거 같습니다

2022-03-03 13:28 UTC, cozynye commented on src/screens/Main.tsx
> +  right: -30px;
텍스트 위치가 왼쪽에 붙어있어서 거리를 두려고 설정했습니다~

2022-03-03 13:30 UTC, cozynye commented on src/module/auth.ts
> +  action: {type: string; payload: string},
토큰의 값이 string이라서 설정했는데 혹시 다른 형식으로도 저장을 해야할까요?

2022-03-03 13:31 UTC, cozynye commented on src/screens/SignIn.tsx
> +      await fetch('http://44.203.41.15:8000/users/signin', {
상수로 선언했습니다!

2022-03-03 13:32 UTC, cozynye commented on src/screens/SignIn.tsx
> +          if (data.result === 'True') {
일단은 문자열로 넘어와서 True로 했습니다 지연님과 조정이 필요할 것 같습니다!

2022-03-03 13:35 UTC, cozynye commented
> 이 PR은 규모가 너무 큽니다.
> 
> `feature/signup`이라고 브랜치를 생성했다면, `signup`과 관련된 기능만 있어야하는데, 여기에는 `signup`, `signin`, `signin` 후에 보여지는 화면까지 포함되어 있습니다.
> 
> 처음에 PR올리실 때 내용을 읽어보고 comment를 했어야했는데 놓쳤네요. 내일 자세히 말씀 드리겠습니다!

2022-03-03 13:35 UTC, cozynye commented
> > 이 PR은 규모가 너무 큽니다.
> > `feature/signup`이라고 브랜치를 생성했다면, `signup`과 관련된 기능만 있어야하는데, 여기에는 `signup`, `signin`, `signin` 후에 보여지는 화면까지 포함되어 있습니다.
> > 처음에 PR올리실 때 내용을 읽어보고 comment를 했어야했는데 놓쳤네요. 내일 자세히 말씀 드리겠습니다!

2022-03-03 13:36 UTC, cozynye commented
다음 화면부터는 브랜치 관리에 신경쓰겠습니다!

2022-03-04 01:27 UTC, merged