(곽승현) Add: Add signup page view
cozynye/WebRTC-APPLICATION-frontend pull request #2
Opened 2022-02-28 08:06 UTC by hyunkark

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
-  회원가입 페이지의 룩 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- Entry.tsx 페이지의 navigation props의 타입 지정
  - 우선 구글링을 해서 나온 블로그를 참조해서 고쳤습니다.
  - interface Props {} 에서 navigation의 타입을 지정하는 것 같은데, StackNavigationProp뒤의 <AuthStackParamList> 가 무엇을 하는 지는 아직 파악하지 못했습니다.
 
1. 회원가입 페이지의 룩 구현
- React Native를 이용해 회원가입 페이지의 룩 구현
- styled-components를 이용해 css를 만듦
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 현재 설정해 둔 절대경로로 컴포넌트나 파일을 가져오려고 하면 해당 파일을 찾을 수 없는 오류가 나고 있어 theme과 컴포넌트를 import하지 못하고 있습니다. 해당 부분 좀 더 공부해 수정할 수 있도록 하겠습니다.
- Typescript의 문법에 익숙치 않아 헤매고 있는 부분이 많습니다. 해당 사항도 속히 익혀서 추후 개발 스케줄에 누가 되지 않도록 하겠습니다.

<br />

## :: 기타 질문 및 특이 사항
- TextInput 컴포넌트를 적용
- theme 적용

2022-02-28 08:13 UTC, hyunkark commented on src/screens/SignUp.tsx
> +          />
추후에 중복 없이 component를 불러와 쓸 수 있도록 고치겠습니다!

2022-02-28 09:07 UTC, jasonkang14 requested changes

2022-02-28 09:07 UTC, jasonkang14 commented on src/components/StyledTextInput.tsx
> +  const [text, onChangeText] = React.useState(null);
`FC`를 import 한 것과 유사하게, `useState`도 아래와 같이 import 할 수 있습니다
```typescript
import React, {FC, useState} from 'react';
```

2022-02-28 09:07 UTC, jasonkang14 commented on src/screens/SignUp.tsx
> +const StyledTextInput = styled.TextInput`
`StyledTextInput`을 `components에 선언했다면 해당 컴포넌트를 사용하는게 좋을 것 같습니다.

2022-02-28 09:07 UTC, jasonkang14 commented on src/screens/SignUp.tsx
> +        <StyledButton title="회원가입 완료" />
`FunctionComponent`에는 `children`이라는 prop이 있습니다. 
```typescript
<StyledButton>회원가입 완료</StyleldButton>
```
위와 같은 형식으로 사용할 수 있습니다. 

회원가입에 사용되는 버튼이니 변수명도 
`StyledButton` 보다는 `SignupButton`이 좋겠네요

2022-02-28 09:07 UTC, jasonkang14 commented on src/screens/SignUp.tsx
> +const StyledSafeArea = styled.SafeAreaView`
접두사에 `Styled`를 붙이신 것은 `styled-components`공식 문서를 참고하셨기 때문이라고 생각합니다. 
일반적을 `Styled`를 앞에 붙이는 경우는 공용 스타일을 선언하고 import해서 가져올 때 사용합니다. 

예를 들면 저희는 많은 버튼들이 `border-radius:4px`로 되어있는데
해당 값을 반복적으로 선언하지 않기 위해서 사용됩니다. 
```typescript
const StyledButton = styled.TouchableOpacity`
  border-radius: 4px;
`

const SignupButton = styled(StyledButton)`
  color: white;
`
```

위와 같이 작성하면 `SignupButton`에도 `border-radius: 4px`의 속성이 적용됩니다. 
참고하셔서 변수명을 수정해주세요

2022-02-28 09:07 UTC, jasonkang14 commented on src/screens/SignUp.tsx
> +  width: 83%;
83%는 어떤 수치인가요?

2022-02-28 09:07 UTC, jasonkang14 commented on src/styles/theme.js
> +import {DefaultTheme} from 'styled-components/native';
typescript를 사용하니 확장자명을 `.ts`로 수정해주세요

2022-02-28 09:26 UTC, hyunkark commented on src/screens/SignUp.tsx
> +  width: 83%;
네, zeplin에서 확인했을 때 TextInput를 비롯한 화면 내의 컨텐츠의 너비가 300px이며, 이를 %로 치환하면 83%가 되는 것을 확인했습니다.
핸드폰의 경우 다양한 크기의 디바이스가 많아 디바이스 별로 일일이 컨텐츠의 너비를 선언해주는 것이 비효율적이라고 생각해 디바이스 화면이 현재의 simulator보다 작은 경우, 현재와 비슷하게 보일 수 있도록 설정을 한 것입니다.

보통 max-width와 width를 같이 써서 페이지 내의 컨텐츠가 일정한 비율로 보이도록 유지하고, 페이지의 넓이가 일정 수준을 넘어가면 가독성을 위해 현재 상태를 유지하도록 쓰는 방법은 웹개발에서는 많이 쓰이는 것으로 알고 있는데요, 추후 리서치를 통해 앱에서의 컨벤션을 찾아내 해당 컨벤션으로 수정하는 방향으로 하겠습니다.

2022-03-01 15:37 UTC, Enjoywater commented on src/screens/SignUp.tsx
> +  display: flex;
`display: flex`가 기본값으로 되어있기 때문에 작성할 필요가 없습니다
또한 위와 같은 layout은 `flex: number`로 간단히 작성할 수 있습니다

2022-03-02 04:20 UTC, jasonkang14 commented on src/screens/SignUp.tsx
> +  width: 83%;
음 네네 그런 경우라면 전체 화면에서 패딩을 주고(좌우 패딩값이 고정일거에요) TextInput에 height를 고정하고 flex:1을 주는 방식이 더 리액트 네이티브 다운 방식일 것 같습니다. 

[공식문서 예제](https://reactnative.dev/docs/flexbox#align-items)를 보면 `width: auto`를 사용하네요

2022-03-02 04:33 UTC, hyunkark commented on src/screens/SignUp.tsx
> +  width: 83%;
넵! 리액트 네이티브에서는 %나 px을 최대한 피하고 flex : number을 이용해서 화면 구현을 하는군요..! 주신 피드백 참고해서 고쳐보도록 하겠습니다!

2022-03-02 07:39 UTC, hyunkark commented on src/screens/SignUp.tsx
> +  display: flex;
넵! 말씀주신 리뷰 적용해 전반적인 레이아웃을 flex로 할 수 있도록 바꿨습니다!

2022-03-02 07:42 UTC, hyunkark commented on src/screens/SignUp.tsx
> +        <StyledButton title="회원가입 완료" />
<Button>컴포넌트의 경우 커스텀할 수 있는 부분이 굉장히 적다고 공식 문서에서 보아서 해당 부분은 TouchableOpacity로 수정했습니다!

2022-03-02 09:36 UTC, Enjoywater commented on src/screens/SignUp.tsx
> +                placeholder={'성을 입력해주세요'}
특정 변수가 아닌 기본 텍스트에는 중괄호`{}`를 넣지 않아도 됩니다

2022-03-03 01:23 UTC, hyunkark commented on src/screens/SignUp.tsx
> +                placeholder={'성을 입력해주세요'}
넵! 수정하겠습니다!

2022-03-03 01:42 UTC, jasonkang14 requested changes

2022-03-03 01:42 UTC, jasonkang14 commented on src/screens/Entry.tsx
> +  justify-content: center;
굳굳 좋습니다

2022-03-03 01:42 UTC, jasonkang14 commented on src/components/SignUpTextInput.tsx
> +  signUpText,
이 prop을 `Label`로 해주면 가독성에 도움이 될 것 같습니다. 
styled component의 이름도 유사하게 변경하면 좋을 것 같아요!

2022-03-03 01:42 UTC, jasonkang14 commented on src/components/SignUpTextInput.tsx
> +  baseText = null,
`baseText`의 type이 `string`이니 default 값도 empty string이면 좋을 것 같습니다.

2022-03-03 01:48 UTC, jasonkang14 commented on src/components/SignUpTextInput.tsx
> +  signUpText,
[HTML Label](https://www.w3schools.com/tags/tag_label.asp)과 유사한 느낌으로요!

2022-03-03 01:48 UTC, hyunkark commented on src/components/SignUpTextInput.tsx
> +  signUpText,
넵! 수정하겠습니다!

2022-03-03 08:18 UTC, jasonkang14 commented
force push를 한 이유가 있나요?

2022-03-03 08:21 UTC, hyunkark commented
> force push를 한 이유가 있나요?

현재 git rebase를 통해 commit을 squash해서 깃을 관리하고 있습니다!
Rebase를 했을 때 미리 conflict를 해결해 놓으니, merge를 했을 때 conflict가 없어 편했기 때문에 이 방법을 쓰고 있습니다.

2022-03-03 08:31 UTC, hyunkark commented on src/screens/SignUp.tsx
> +              </View>
최대한 컴포넌트를 재활용 하고, input 컴포넌트 안의 value들을 전역 상태 관리 툴을 이용해 관리하고 싶었습니다. 하지만 아직 redux 사용이 서툴어서 의도하던 바대로 전역 관리를 할 수 없었습니다.
우선은 백엔드와의 통신을 최우선으로 놓고, 내일 redux를 이용해 상태관리 하는 방법을 강구해 볼 생각입니다.

2022-03-03 09:15 UTC, merged