[곽승현] Fix states to validate input datas and send datas to backend
cozynye/WebRTC-APPLICATION-frontend pull request #3
Opened 2022-03-04 08:00 UTC by hyunkark

### 최근 작업 주제

- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ]  컨벤션 수정

### 구현 목표
회원가입 페이지의 input data를 관리, data를 validate한 후에 백으로 보내기

### 구현 사항 설명 

- input에 입력한 data를 state에 넣어서 관리
- 비밀번호가 양식에 맞게 입력되도록 표현식을 이용해 관리, 양식에 맞지 않으면 경고문을 보여줌
- 비밀번호와 비밀번호 확인 칸의 데이터가 일치하지 않으면 경고문을 보여줌
- input에 모든 데이터가 입력되어 있고, 비밀번호가 양식에 맞으며 일치할 때만 회원가입 버튼이 활성화 되도록 만듦
- 이메일의 양식이 맞지 않거나 이미 등록되어 있는 이메일이면 서버에서 보내주는 메시지에 따라 이메일의 양식을 고치거나, 새로운 이메일을 쓰도록 경고문을 보여줌
- 회원가입에 성공하면 자동으로 로그인을 해서 토큰을 state에 받아줌

### 기타 질문 및 특이 사항
- 현재 기능은 작동하나 주말동안 redux를 활용해 코드를 고쳐보고자 합니다. Redux에 관한 것이 아직 감이 잡히지 않아 학습과 병행하겠습니다!

2022-03-04 08:48 UTC, Enjoywater requested changes

2022-03-04 08:48 UTC, Enjoywater commented on src/screens/SignUp.tsx
> +  const [emailWarningText, setEmailWarningText] = React.useState(true);
위에서 `import` 하셨기때문에 `React.`은 붙이지 않으셔도 됩니다.
또한 여러개의 `state값`은 상단에 한번에 작성하시는게 좋습니다 !

2022-03-04 08:48 UTC, Enjoywater commented on src/screens/SignUp.tsx
> +                secureTextEntry={showPw.pwVerify ? true : false}
`showPw.pwVerify`값이 `boolean`이기 때문에 `삼항연사자`는 쓰지 않으셔도 됩니다.

2022-03-04 08:48 UTC, Enjoywater commented on src/screens/SignUp.tsx
> +                password: textInputs.password,
textInputs을 구조분해 하시면 아래처럼 작성가능합니다.
```
JSON.stringify({
                email,
                password,
              })
```

2022-03-04 08:48 UTC, Enjoywater commented on src/screens/SignUp.tsx
> +    console.log('hi');
`pr`을 올릴때는 `console`은 삭제해주세요 !

2022-03-04 08:48 UTC, Enjoywater commented on src/screens/SignUp.tsx
> +
구조분해가 가능한 부분에서는 적극적으로 사용해서 가독성을 높게할 수 있습니다

2022-03-04 08:52 UTC, hyunkark commented on src/screens/SignUp.tsx
> +                password: textInputs.password,
email: email로 쓰지 않아도 그냥 email을 쓰면 알아서 email: textInputs.email이 들어가는군요...! 참고해서 고치겠습니다! 리뷰 감사합니다!😄

2022-03-04 08:53 UTC, LEEYEONSEONG requested changes

2022-03-04 08:53 UTC, LEEYEONSEONG commented on src/screens/SignUp.tsx
> +  const pwRegEx: RegExp = '^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z@$!%*?&\\d]{8,}$';
`pwRegEx` 를 사용하는 변수 `isPwCerified` 안으로 이동 시켜 주세요.
render가 일어나는 구분마다 연산이 이루어져서 문제가 될 수 있습니다.

2022-03-04 08:53 UTC, LEEYEONSEONG commented on src/screens/SignUp.tsx
> +      fetch('http://44.203.41.15:8000/users/signup', {
fetch 함수를 통해 서버와 통신할 때 API 주소 는 global directory를 만들어 export로 관리하는게 좋습니다.

작은 프로젝트일때는 상관이 없지만 만약 프로젝트가 커지고 API를 수정 하고자 할때 다른 해당 파일들을 전부 수정 해야하는 번거로움이 있고 팀 단위로 진행 할 경우 팀원들의 API 주소도 변경해야 하는 이슈도 생길수 있습니다. 

이를 방지하고자 공통으로 사용할 수 있는 config.js 및 global 파일을 생성하여 API 주소를 관리하면 주소가 변경되어도 그 해당 파일 주고만 변경하면 모든 주소애 적용되기 때문에 합리적으로 관리 할 수 있습니다.

2022-03-04 08:53 UTC, LEEYEONSEONG commented on src/screens/SignUp.tsx
> +  const checkPwVerified = isPwVerified();
위에 와 마찬가지로 사용하는 함수로 넣어 주세요.

2022-03-04 08:55 UTC, hyunkark commented on src/screens/SignUp.tsx
> +  const pwRegEx: RegExp = '^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z@$!%*?&\\d]{8,}$';
리뷰 감사드립니다! 말씀주신 부분 반영해 코드 수정하겠습니다! 🙌

2022-03-04 08:56 UTC, jasonkang14 requested changes

2022-03-04 08:56 UTC, jasonkang14 commented on src/screens/SignUp.tsx
> +  const pwRegEx: RegExp = '^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z@$!%*?&\\d]{8,}$';
`pwRegEx`가 필요한 함수는 하나인데, 함수 밖에서 선언하게되면 re-render가 일어날 때마다 새로운 변수가 선언되고 할당됩니다. 
scope를 고려해서 해당 변수가 필요한 함수 내부로 이동시켜주세요.

2022-03-04 08:56 UTC, jasonkang14 commented on src/screens/SignUp.tsx
> +  const checkPwVerified = isPwVerified();
여기도 `pwRegEx`를 선언한 부분과 같습니다. 비밀번호 verify는 비밀번호 Input에 값이 변할 때 확인해야하는데, 
effect hook 밖에서 변수/함수를 실행/선언하면 이메일을 입력할때도 함수를 계속 실행시켜 비효율적입니다.

2022-03-04 08:56 UTC, jasonkang14 commented on src/screens/SignUp.tsx
> +    if (submitDisabled === false) {
boolean값은 [!](https://stackoverflow.com/a/8012020)를 사용해서 구분할 수 있습니다.

2022-03-04 08:56 UTC, jasonkang14 commented on src/screens/SignUp.tsx
> +      fetch('http://44.203.41.15:8000/users/signup', {
API주소는 환경변수를 사용해주세요

2022-03-04 08:59 UTC, hyunkark commented on src/screens/SignUp.tsx
> +    if (submitDisabled === false) {
리뷰 감사드립니다! 참고해서 수정할 수 있도록 하겠습니다!

2022-03-04 09:04 UTC, Enjoywater commented on src/screens/SignUp.tsx
> +                password: textInputs.password,
**단축속성명** 입니다 !

2022-03-07 07:23 UTC, Enjoywater requested changes

2022-03-07 07:23 UTC, Enjoywater commented on src/module/signUp.ts
> +}
[redux style guide](https://redux.js.org/style-guide/style-guide/#write-actions-using-the-flux-standard-action-convention)를 보시면 `FSA convention` 이 있습니다.
앞으로 `action`을 만들때에도 참고해주시고, `return`값을 수정해주세요.

2022-03-07 07:23 UTC, Enjoywater commented on src/screens/SignUp.tsx
> +  }, [textInputs]);
`dependency` 관련해서 `warning`이 발생하지는 않았나요?

2022-03-07 07:23 UTC, jasonkang14 commented on src/api/config.ts
> +  fetchLogin: BASE_URL + 'users/signin',
수녕님과 같은 파일명에서 다른 이름으로 객체가 선언되어있네요. 
수녕님 코드는 main에 merge되었으니, main브랜치를 머지하셔서 수녕님 코드를 반영해주세요

2022-03-07 07:23 UTC, jasonkang14 commented on src/module/signUp.ts
> +    payload: data,
data와 datatype도 타입을 상세히 정해주면 좋을 것 같습니다. 
예를들면 initial state에 값들이라면 `surname`, `name`, `email`, `password`등의 값들을 선언하는 것이 가독성에 좋을 것 같습니다. 
그리고 datatype이라는 변수가 이름만 보기에는 굉장히 모호해서, 조금 더 구체적으로 변수명을 설정해주실 수 있나요?

2022-03-07 07:23 UTC, jasonkang14 commented on src/module/signUp.ts
> +  action: {type: string; payload: string; datatype: string},
이런 경우라면 `datatype`의 type을 `'surname' | 'name' | 'email' | 'password'`로 고정하는 편이 좋습니다. 

1. `signup.tsx`에서는 이 값들을 dispatch하는 부분이 없고,
2. 회원가입이 한 화면에서만 이루어져서 굳이 전역변수로 해당 값들을 관리하지 않아도 될 것 같은데 

리덕스를 사용하신 이유를 설명해주실 수 있나요?

2022-03-07 07:30 UTC, hyunkark commented on src/module/signUp.ts
> +  action: {type: string; payload: string; datatype: string},
signup.tsx 파일이 너무 길고 복잡해서 코드를 읽기에 좋지 않은 것 같아 관심사의 분리를 위해 리덕스를 쓰려고 했습니다. 말씀주신 대로 회원가입에 쓰이는 states는 회원가입에서만 사용되는 정보인지라 차라리 커스텀 훅을 쓰는 게 좋은 방법일까 하는 고민이 있습니다.

2022-03-07 07:35 UTC, hyunkark commented on src/screens/SignUp.tsx
> +  }, [textInputs]);
발생했습니다...! 린터가 말해준 대로 고치긴 했는데 함수 형태인 isPwValid() 함수를 dependency로 추가하면 maximum update depth exceeded에러가 떠서 isPwValid는 제외하고 dependency에 추가했습니다!

2022-03-07 08:01 UTC, Enjoywater commented on src/screens/SignUp.tsx
> +  }, [textInputs]);
`dependency`에 추가하지 않고 함수 자체를 `effect hook` 내부로 위치시키는것도 방법이 될 수 있습니다.
[useEffect guide](https://overreacted.io/a-complete-guide-to-useeffect/) 해당 링크에서 
**Question: Do I need to specify functions as effect dependencies or not?** 부분을 확인해보세요!

2022-03-07 08:02 UTC, hyunkark commented on src/screens/SignUp.tsx
> +  }, [textInputs]);
감사합니다! 말씀주신 링크 참조해서 고쳐보도록 하겠습니다!

2022-03-07 08:33 UTC, hyunkark commented on src/module/signUp.ts
> +  action: {type: string; payload: string; datatype: string},
커스텀 훅을 쓰기에는 해당 로직을 재사용 하는 곳이 없어 그냥 이대로 두고자 합니다! 코멘트 감사합니다!

2022-03-07 13:05 UTC, jasonkang14 approved these changes
template literal만 수정해주시면 머지하겠습니다!

2022-03-07 13:05 UTC, jasonkang14 commented on src/config.ts
> +  signUp: baseUri + 'users/signup',
포맷을 통일하면 좋을 것 같습니다 여기도 .template literal을 사용해주세요

2022-03-08 01:13 UTC, hyunkark commented on src/config.ts
> +  signUp: baseUri + 'users/signup',
template literal 방식으로 수정했습니다! 이번 PR도 리뷰 감사드립니다!

2022-03-08 03:58 UTC, jasonkang14 approved these changes
LGTM

2022-03-08 03:58 UTC, merged