[신수녕] http 통신 에러 핸들링 추가
cozynye/WebRTC-APPLICATION-frontend pull request #4
Opened 2022-03-04 08:47 UTC by cozynye

### 최근 작업 주제

- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ]  컨벤션 수정

### 구현 목표
- 로그인 페이지 통신 후 에러 핸들링 

### 구현 사항 설명 
- 아이디, 비밀번호 오류 시 throw new Error를 통해 catch문으로 넘어가도록 로직 설정
- catch에서 받은 에러 메시지로 alert 경고창 설정

### 기타 질문 및 특이 사항

2022-03-04 08:55 UTC, LEEYEONSEONG requested changes

2022-03-04 08:55 UTC, LEEYEONSEONG commented on src/screens/SignIn.tsx
> +  console.log('asdf');
console.log()는 삭제해주세요.!

2022-03-04 08:57 UTC, jasonkang14 commented
`.vscode` directory는 `.gitignore`에 추가해주세요

2022-03-04 08:58 UTC, jasonkang14 requested changes

2022-03-04 08:58 UTC, jasonkang14 commented on src/screens/Entry.tsx
> +  padding: 13px 126px;
패딩의 목적이 가운데 정렬이라면 flexbox의 속성들을 사용해주세요

2022-03-04 09:00 UTC, Enjoywater requested changes

2022-03-04 09:00 UTC, Enjoywater commented on src/module/auth.ts
> +type Type = ReturnType<typeof userLogin>;
너무 포괄적이지 않도록 변수명에 action이 포함되는게 좋을 것 같습니다.

2022-03-04 09:00 UTC, Enjoywater commented on src/screens/SignIn.tsx
> +    } catch (err: any) {
`any`는 지양하고 `error`의 고유한 `type`으로 작성해주세요

2022-03-04 09:00 UTC, Enjoywater commented on src/screens/SignIn.tsx
구조분해가 가능한 부분에서는 적극적으로 사용해서 가독성을 높게할 수 있습니다

2022-03-04 09:00 UTC, Enjoywater commented on src/screens/SignIn.tsx
>            password: inputState.password,
승현님과 마찬가지로 **구조분해**와 **단축속성명**을 사용해보세요!

2022-03-04 09:05 UTC, cozynye commented on src/screens/Entry.tsx
> +  padding: 13px 126px;
크기를 맞추려고 패딩을 사용했습니다!

2022-03-04 09:53 UTC, cozynye commented on src/screens/SignIn.tsx
dispatch 부분이 구조분해가 가능한 것인가요?

2022-03-04 09:55 UTC, Enjoywater commented on src/screens/SignIn.tsx
아아 아뇨! 
제가 빈공간에 리뷰를 달아서 오해가 있었던거 같아요
전체적으로 가능한 부분을 말씀드리려고 한거였어요!

2022-03-04 09:58 UTC, cozynye commented on src/screens/SignIn.tsx
알겠습니다!!!! 😄

2022-03-04 10:24 UTC, jasonkang14 commented
수녕님 브랜치가 feature/signup이네요 다음 PR부터는 기능에 맞게 설정 부탁 드립니다

2022-03-05 13:44 UTC, cozynye commented
네 알겠습니다! 다음에는 브랜치 수정하겠습니다!

2022-03-07 01:10 UTC, jasonkang14 requested changes

2022-03-07 01:10 UTC, jasonkang14 commented on src/screens/Entry.tsx
> +  padding: 13px 126px;
세로는 괜찮은데, 가로길이는 디바이스 사이즈가 다르면 문제가 있을거에요. 
지금 디바이스 하나로만 확인 중이실 걸로 예상 되는데, 
지금 확인하시는 것보다 작은 걸로 확인하시면 버튼이 화면을 넘어갈거고, 
지금보다 큰걸로 확인한다면 디자인에 맞지 않게 좌우 공백이 크게 나타날겁니다. 

`SignUpButton`에도 유사하게 작업했는데 놓쳤네요. 
React Native StyleSheet에는 적용할 수 없지만, styled component를 사용중이니, 
전체 View에 패딩을 넣고, 버튼에는 `width: 100%`를 넣는다던지, 
아니면 버튼의 width를 `devicewidth - (전체화면 패딩)`으로 잡아야 다양한 디바이스 사이즈에 대응할 수 있습니다.

2022-03-07 01:10 UTC, jasonkang14 commented on src/screens/SignIn.tsx
> +  console.log('dispatch');
`console.log()`를 제거해주세요

2022-03-07 01:10 UTC, jasonkang14 commented on src/config.ts
> +  fetchLogin: `${baseURI}users/signin`,
객체의 이름이 `fetchAPI`이니, 객체의 key 값에서는 `fetch`라는 단어를 빼도 좋을 것 같습니다.

2022-03-07 01:28 UTC, cozynye commented
버튼을 감싼 뷰 width를 70% 센트로 하고 버튼의 width를 100%로 했는데 이렇게 해도 괜찮을 까요?

2022-03-07 01:59 UTC, jasonkang14 requested changes

2022-03-07 01:59 UTC, jasonkang14 commented on src/config.ts
> +  Login: `${baseURI}users/signin`,
camelCase를 사용을 위해 소문자로 변경해주세요.

2022-03-07 02:02 UTC, cozynye commented on src/config.ts
> +  Login: `${baseURI}users/signin`,
수정했습니다!

2022-03-07 04:15 UTC, jasonkang14 requested changes

2022-03-07 04:15 UTC, jasonkang14 commented on src/config.ts
> +  Login: `${baseUri}users/signin`,
camel case사용을 위해 변수의 첫 글자를 소문자로 변경해주세요. 
그리고 모든 화면에서 signin이라는 단어가 활용되니
API객체의 키값도 signin으로 변경하는 것이 좋을 것 같습니다.

2022-03-07 04:30 UTC, cozynye commented on src/config.ts
> +  Login: `${baseUri}users/signin`,
수정했습니다!

2022-03-07 05:35 UTC, jasonkang14 approved these changes
LGTM

2022-03-07 05:35 UTC, merged